const kn = {
  common: {
    appName: 'ಫಿಂಕ್ಲಾರಿಯೋ', tagline: 'ನಿಮ್ಮ ಹಣಕಾಸಿನ ಸ್ಪಷ್ಟತೆ.', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡು', delete: 'ಅಳಿಸಿ', edit: 'ತಿದ್ದುಪಡಿ ಮಾಡಿ', close: 'ಮುಚ್ಚಿ', viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ →', apply: 'ಅನ್ವಯಿಸು', reset: 'ಮರುಹೊಂದಿಸು', search: 'ಹುಡುಕು', filter: 'ಫಿಲ್ಟರ್', filters: 'ಫಿಲ್ಟರ್‌ಗಳು', export: 'ರಫ್ತು', download: 'ಡೌನ್‌ಲೋಡ್', email: 'ಇಮೇಲ್', password: 'ಪಾಸ್‌ವರ್ಡ್', signIn: 'ಸೈನ್-ಇನ್', signUp: 'ಸೈನ್-ಅಪ್', signOut: 'ಸೈನ್-ಔಟ್', or: 'ಅಥವಾ', allBanks: 'ಎಲ್ಲಾ ಬ್ಯಾಂಕುಗಳು', allCategories: 'ಎಲ್ಲಾ ವರ್ಗಗಳು', allTime: 'ಎಲ್ಲಾ ಸಮಯ', noData: 'ಯಾವುದೇ ಮಾಹಿತಿಯಿಲ್ಲ', syncedJustNow: 'ಈಗಷ್ಟೇ ಸಿಂಕ್ ಆಗಿದೆ', syncedAgo: '{{time}} ನಿಮಿಷಗಳ ಹಿಂದೆ', page: 'ಪುಟ', of: 'ನಲ್ಲಿ', showing: 'ತೋರಿಸಲಾಗುತ್ತಿದೆ', total: 'ಒಟ್ಟು',
  },
  nav: { dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', transactions: 'ವಹಿವಾಟುಗಳು', analytics: 'ವಿಶ್ಲೇಷಣೆ', goals: 'ಗುರಿಗಳು', insights: 'AI ಒಳನೋಟಗಳು', schemes: 'ಸಾಲಗಳು & ಯೋಜನೆಗಳು', credit: 'ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್', reports: 'ವರದಿಗಳು', bankaa: 'ಬ್ಯಾಂಕ್ AA', alerts: 'ಎಚ್ಚರಿಕೆಗಳು', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು' },
  login: { title: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಸೈನ್-ಇನ್ ಮಾಡಿ', createAccount: 'ಖಾತೆ ರಚಿಸಿ', emailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ', emailPlaceholder: 'you@example.com', passwordLabel: 'ಪಾಸ್‌ವರ್ಡ್', continueWithGoogle: 'Google ಮೂಲಕ ಮುಂದುವರಿಸಿ', noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್-ಅಪ್ ಮಾಡಿ', hasAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಸೈನ್-ಇನ್ ಮಾಡಿ', welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ!', accountCreated: 'ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ!' },
  dashboard: { totalNetWorth: 'ಒಟ್ಟು ಆಸ್ತಿ ಮೌಲ್ಯ', inThisMonth: 'ಆದಾಯ (ಈ ತಿಂಗಳು)', outThisMonth: 'ಖರ್ಚು (ಈ ತಿಂಗಳು)', doingGreat: 'ನೀವು ಅತ್ಯುತ್ತಮವಾಗಿ ಮಾಡುತ್ತಿದ್ದೀರಿ!', savingsHealthy: 'ಈ ತಿಂಗಳು ನಿಮ್ಮ ಉಳಿತಾಯ ದರ ಆರೋಗ್ಯಕರವಾಗಿದೆ!', connectedAccounts: 'ಸಂಪರ್ಕಿತ ಖಾತೆಗಳು', linkViaSetu: 'Setu AA ಮೂಲಕ ಲಿಂಕ್ ಮಾಡಿ', addManualBank: 'ಮ್ಯಾನ್ಯುವಲ್ ಬ್ಯಾಂಕ್ ಸೇರಿಸಿ', availableBalance: 'ಲಭ್ಯವಿರುವ ಬ್ಯಾಲೆನ್ಸ್', recentTransactions: 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು', noRecentTxns: 'ಯಾವುದೇ ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳಿಲ್ಲ.' },
  txns: { title: 'ಎಲ್ಲಾ ವಹಿವಾಟುಗಳು', showingOf: '{{total}} ನಲ್ಲಿ {{filtered}} ತೋರಿಸಲಾಗುತ್ತಿದೆ', exportCSV: 'CSV ರಫ್ತು', searchPlaceholder: 'ವ್ಯಾಪಾರಿಗಳು, ವರ್ಗಗಳನ್ನು ಹುಡುಕಿ...', date: 'ದಿನಾಂಕ', merchant: 'ವ್ಯಾಪಾರಿ / ವಿವರಗಳು', category: 'ವರ್ಗ', bank: 'ಬ್ಯಾಂಕ್', amount: 'ಮೊತ್ತ', noMatch: 'ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ವಹಿವಾಟುಗಳಿಲ್ಲ.', totalIn: 'ಒಟ್ಟು ಆದಾಯ', totalOut: 'ಒಟ್ಟು ಖರ್ಚು', last7Days: 'ಕಳೆದ 7 ದಿನಗಳು', last30Days: 'ಕಳೆದ 30 ದಿನಗಳು', last90Days: 'ಕಳೆದ 90 ದಿನಗಳು' },
  analytics: { spentThisMonth: 'ಈ ತಿಂಗಳು ಖರ್ಚು', incomeThisMonth: 'ಈ ತಿಂಗಳು ಆದಾಯ', topCategory: 'ಟಾಪ್ ವರ್ಗ', savingsRate: 'ಉಳಿತಾಯ ದರ', incomeVsExpense: 'ಆದಾಯ vs ಖರ್ಚು', income: 'ಆದಾಯ', expense: 'ಖರ್ಚು', spendingSnapshot: 'ಖರ್ಚಿನ ಸಾರಾಂಶ', totalSpent: 'ಒಟ್ಟು ಖರ್ಚು', netSavingsGrowth: 'ನಿವ್ವಳ ಉಳಿತಾಯ ಬೆಳವಣಿಗೆ', netSavings: 'ನಿವ್ವಳ ಉಳಿತಾಯ' },
  goals: { title: 'ಆರ್ಥಿಕ ಗುರಿಗಳು', subtitle: 'ನಿಮ್ಮ ಉಳಿತಾಯ ಗುರಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ', newGoal: 'ಹೊಸ ಗುರಿ', addNewGoal: 'ಹೊಸ ಗುರಿ ಸೇರಿಸಿ', goalName: 'ಗುರಿಯ ಹೆಸರು', targetAmount: 'ಗುರಿ ಮೊತ್ತ (₹)', currentSaved: 'ಪ್ರಸ್ತುತ ಉಳಿತಾಯ (₹)', eta: 'ಅಂದಾಜು ಸಮಯ', saveGoal: 'ಗುರಿಯನ್ನು ಉಳಿಸಿ', target: 'ಗುರಿ', goalReached: 'ಗುರಿ ತಲುಪಲಾಗಿದೆ! 🎉' },
  ai: { title: 'AI ಆರ್ಥಿಕ ಒಳನೋಟಗಳು', subtitle: 'ನಿಮ್ಮ ಖರ್ಚಿನ ಡೇಟಾದಿಂದ बुद्धिमत्ता', spendingPrediction: '📈 ಖರ್ಚಿನ ಮುನ್ಸೂಚನೆ', categoryIntelligence: '🧠 ವರ್ಗ बुद्धिमत्ता', generatedInsights: '💡 ರಚಿತ ಒಳನೋಟಗಳು', notEnoughData: 'ಸಾಕಷ್ಟು ಡೇಟಾ ಇಲ್ಲ', newInsights: '{{count}} ಹೊಸತು' },
  schemes: { title: 'ಸಾಲಗಳು & ಯೋಜನೆಗಳು', subtitle: 'ವೈಯಕ್ತಿಕ ಸಬ್ಸಿಡಿಗಳು ಮತ್ತು ಸಾಲ ಅವಕಾಶಗಳನ್ನು ಅನ್ವೇಷಿಸಿ', personalizedRec: 'ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳು', applyNow: 'ಈಗಲೇ ಅನ್ವಯಿಸಿ', viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ', match: 'ಹೊಂದಾಣಿಕೆ', all: 'ಎಲ್ಲವೂ', government: 'ಸರ್ಕಾರಿ', agriculture: 'ಕೃಷಿ', education: 'ಶಿಕ್ಷಣ', housing: 'ವಸತಿ', business: 'ವ್ಯಾಪಾರ' },
  credit: { title: 'ಕ್ರೆಡಿಟ್ ಪ್ರೊಫೈಲ್', subtitle: 'ನಿಮ್ಮ ಕ್ರೆಡಿಟ್ ಆರೋಗ್ಯವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ', experianScore: '📊 ನಿಮ್ಮ ಎಕ್ಸ್‌ಪೀರಿಯನ್ ಸ್ಕೋರ್', veryGood: 'ಬಹಳ ಒಳ್ಳೆಯದು', paymentHistory: 'ಪಾವತಿ ಇತಿಹಾಸ', creditUtilization: 'ಕ್ರೆಡಿಟ್ ಬಳಕೆ', totalAccounts: 'ಒಟ್ಟು ಖಾತೆಗಳು', hardInquiries: 'ಕಠಿಣ ವಿಚಾರಣೆಗಳು', highImpact: 'ಹೆಚ್ಚಿನ ಪ್ರಭಾವ', lowImpact: 'ಕಡಿಮೆ ಪ್ರಭಾವ', scoreSimulator: '🔬 ಸ್ಕೋರ್ ಸಿಮ್ಯುಲೇಟರ್', projectedScore: 'ಅಂದಾಜು ಸ್ಕೋರ್', simulatorDesc: 'ನಿಮ್ಮ ಸ್ಕೋರ್ ಮೇಲಿನ ಪ್ರಭಾವವನ್ನು ನೋಡಲು ಬದಲಾವಣೆಗಳನ್ನು ಮಾಡಿ.', payDebt: 'ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್ ಸಾಲ ₹50,000 ಪಾವತಿಸಿ', payDebtDesc: 'ಕ್ರೆಡಿಟ್ ಬಳಕೆಯನ್ನು ಗಣನೀಯವಾಗಿ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ', newCard: 'ಹೊಸ ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್‌ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ', newCardDesc: 'ತಾತ್ಕಾಲಿಕ ಕುಸಿತ', missPayment: '30 ದಿನಗಳ ಪಾವತಿಯನ್ನು ತಪ್ಪಿಸಿ', missPaymentDesc: 'ಪಾವತಿಯ ಇತಿಹಾಸದ ಮೇಲೆ ಗಂಭೀರ ಪ್ರಭಾವ' },
  reports: { title: 'ಆರ್ಥಿಕ ವರದಿಗಳು', subtitle: 'ನಿಮ್ಮ ಹಣಕಾಸು ಡೇಟಾವನ್ನು ರಫ್ತು ಮಾಡಿ ಮತ್ತು ಹಂಚಿಕೊಳ್ಳಿ', reportType: 'ವರದಿಯ ಪ್ರಕಾರ', dateRange: 'ದಿನಾಂಕದ ವ್ಯಾಪ್ತಿ', thisMonth: 'ಈ ತಿಂಗಳು', last3Months: 'ಕಳೆದ 3 ತಿಂಗಳುಗಳು', includedAccounts: 'ಸೇರಿಸಲಾದ ಖಾತೆಗಳು', allConnectedBanks: 'ಎಲ್ಲಾ ಸಂಪರ್ಕಿತ ಬ್ಯಾಂಕುಗಳು', downloadPDF: 'PDF ಡೌನ್‌ಲೋಡ್', exportCSV: 'CSV ಆಗಿ ರಫ್ತು ಮಾಡಿ', emailToSelf: 'ಇಮೇಲ್ ಮಾಡಿ', shareLink: 'ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ', reportReady: 'ನಿಮ್ಮ ವರದಿ ಸಿದ್ಧವಾಗಿದೆ.', incomeExpenseSummary: 'ಆದಾಯ & ಖರ್ಚಿನ ಸಾರಾಂಶ', taxSaving: 'ತೆರಿಗೆ ಉಳಿತಾಯದ ವರದಿ', allTransactions: 'ಎಲ್ಲಾ ವಹಿವಾಟುಗಳ ಪಟ್ಟಿ', categorySpend: 'ವರ್ಗದ ಖರ್ಚು ವಿಶ್ಲೇಷಣೆ' },
  alerts: { title: 'ಅಧಿಸೂಚನೆಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು', subtitle: 'ನಿಮ್ಮ ಸಂಪರ್ಕಿತ ಖಾತೆಗಳಿಂದ ರಚಿತವಾದ ಸ್ಮಾರ್ಟ್ ಒಳನೋಟಗಳು.', markAllRead: 'ಎಲ್ಲವನ್ನೂ ಓದಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ', allClear: '✅ ಎಲ್ಲವೂ ಸರಿಯಾಗಿದೆ!', allClearDesc: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ. ಎಲ್ಲವೂ ಸುರಕ್ಷಿತವಾಗಿದೆ.', lowBalance: 'ಕಡಿಮೆ ಬ್ಯಾಲೆನ್ಸ್ ಎಚ್ಚರಿಕೆ', highSpending: 'ಹೆಚ್ಚಿನ ಖರ್ಚು ಪತ್ತೆಯಾಗಿದೆ', largeTransaction: 'ದೊಡ್ಡ ವಹಿವಾಟು ಎಚ್ಚರಿಕೆ', savingStreak: 'ಉಳಿತಾಯದ ಸರಮಾಲೆ!' },
  settings: { title: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', subtitle: 'ನಿಮ್ಮ ಖಾತೆಯ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.', saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ', accountProfile: 'ಖಾತೆ ಪ್ರೊಫೈಲ್', emailField: 'ಇಮೇಲ್', displayName: 'ಪ್ರದರ್ಶನ ಹೆಸರು', appPreferences: 'ಅಪ್ಲಿಕೇಶನ್ ಆದ್ಯತೆಗಳು', darkTheme: 'ಡಾರ್ಕ್ ಥೀಮ್', darkThemeDesc: 'ಡಾರ್ಕ್ ಇಂಟರ್ಫೇಸ್‌ಗೆ ಬದಲಿಸಿ', pushAlerts: 'ಪುಶ್ ಎಚ್ಚರಿಕೆಗಳು', pushAlertsDesc: 'ಸ್ಮಾರ್ಟ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ', defaultCurrency: 'ಡೀಫಾಲ್ಟ್ ಕರೆನ್ಸಿ', inr: 'ಭಾರತೀಯ ರೂಪಾಯಿ (₹ INR)', usd: 'ಯುಎಸ್ ಡಾಲರ್ ($ USD)', connectedDataSources: 'ಸಂಪರ್ಕಿತ ಡೇಟಾ ಮೂಲಗಳು', connectedDataDesc: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಸೇರಿಸಲು ಬ್ಯಾಂಕ್ ಖಾತೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ.', monthlySpendingLimits: 'ಮಾಸಿಕ ಖರ್ಚಿನ ಮಿತಿಗಳು', language: 'ಭಾಷೆ', languageDesc: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ', settingsSaved: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ', needOneBank: 'ನೀವು ಕನಿಷ್ಠ ಒಂದು ಬ್ಯಾಂಕ್ ಖಾತೆಯನ್ನು ಸಂಪರ್ಕಿಸಬೇಕು' },
  bankaa: { linkBankAccounts: 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗಳನ್ನು ಲಿಂಕ್ ಮಾಡಿ', linkBankDesc: 'ಸೆತುವಿನ ಅಕೌಂಟ್ ಅಗ್ರಿಗೇಟರ್ ಫ್ರೇಮ್‌ವರ್ಕ್ ಮೂಲಕ ನಿಮ್ಮ ಖಾತೆಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಪರ್ಕಿಸಿ.', linkButton: 'ನನ್ನ ಬ್ಯಾಂಕ್ ಖಾತೆಗಳನ್ನು ಲಿಂಕ್ ಮಾಡಿ', rbiBadge: 'ಆರ್ ಬಿ ಐ ನಿಯಂತ್ರಿತ • ಅಕೌಂಟ್ ಅಗ್ರಿಗೇಟರ್', setuSandbox: 'ಸೆತು AA ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್', multiBankView: 'ಬಹು-ಬ್ಯಾಂಕ್ ನೋಟ', multiBankViewDesc: 'ಅನೇಕ ಬ್ಯಾಂಕುಗಳ ಎಲ್ಲಾ ಖಾತೆಗಳನ್ನು ಒಂದೇ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ನೋಡಿ', spendingAnalytics: 'ಖರ್ಚಿನ ವಿಶ್ಲೇಷಣೆ', spendingAnalyticsDesc: 'ಆದಾಯ vs ಖರ್ಚನ್ನು ದೃಶ್ಯ ವಿಭಜನೆಯೊಂದಿಗೆ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ', bankGradeSecurity: 'ಬ್ಯಾಂಕ್-ಗ್ರೇಡ್ ಭದ್ರತೆ', bankGradeSecurityDesc: 'DEPA ಫ್ರೇಮ್‌ವರ್ಕ್ ಮೂಲಕ ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ', connectionError: 'ಸಂಪರ್ಕ ದೋಷ', creatingConsent: 'ಸಮ್ಮತಿ ವಿನಂತಿಯನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...', connectingToSetu: 'ಸೆತು AA ಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ', openingConsent: 'ಸಮ್ಮತಿ ಪುಟವನ್ನು ತೆರೆಯಲಾಗುತ್ತಿದೆ...', approveInTab: 'ಹೊಸ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ಅನುಮೋದಿಸಿ', waitingApproval: 'ಅನುಮೋದನೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ...', completeConsent: 'ಸೆತು ಟ್ಯಾಬ್‌ನಲ್ಲಿ ಸಮ್ಮತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ', fetchingData: 'ಬ್ಯಾಂಕ್ ಡೇಟಾವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...', decryptingFI: 'ಹಣಕಾಸಿನ ಮಾಹಿತಿಯನ್ನು ಡಿಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ', cancelReset: 'ರದ್ದುಮಾಡಿ & ಮರುಹೊಂದಿಸಿ', multiBankDashboard: 'ಬಹು-ಬ್ಯಾಂಕ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', accountsLinked: '{{count}} ಖಾತೆಗಳನ್ನು ಲಿಂಕ್ ಮಾಡಲಾಗಿದೆ', transactionsCount: '{{count}} ವಹಿವಾಟುಗಳು', refresh: 'ರಿಫ್ರೆಶ್', relink: 'ಮತ್ತೆ ಲಿಂಕ್ ಮಾಡಿ', totalBalance: 'ಒಟ್ಟು ಬ್ಯಾಲೆನ್ಸ್', linkedAccounts: 'ಲಿಂಕ್ ಮಾಡಲಾದ ಖಾತೆಗಳು', totalIncome: 'ಒಟ್ಟು ಆದಾಯ', totalSpend: 'ಒಟ್ಟು ಖರ್ಚು', balance: 'ಬ್ಯಾಲೆನ್ಸ್', combinedTransactions: 'ಸಂಯೋಜಿತ ವಹಿವಾಟುಗಳು', description: 'ವಿವರಣೆ', type: 'ಪ್ರಕಾರ', noTxnFilters: 'ಪ್ರಸ್ತುತ ಫಿಲ್ಟರ್‌ಗಳೊಂದಿಗೆ ಯಾವುದೇ ವಹಿವಾಟುಗಳು ಕಂಡುಬಂದಿಲ್ಲ.', incomeVsSpend: 'ಆದಾಯ vs ಖರ್ಚಿನ ವಿಭಜನೆ', netSavings: 'ನಿವ್ವಳ ಉಳಿತಾಯ', creditTxns: '{{count}} ಜಮಾ ವಹಿವಾಟುಗಳು', debitTxns: '{{count}} ಡೆಬಿಟ್ ವಹಿವಾಟುಗಳು' },
  setuModal: { verifyIdentity: 'ಗುರುತನ್ನು ಪರಿಶೀಲಿಸಿ', enterNumber: 'ಬ್ಯಾಂಕ್ ಖಾತೆಗಳಿಗೆ ಲಿಂಕ್ ಮಾಡಲಾದ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ', mobileNumber: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ', sendOTP: 'OTP ಕಳುಹಿಸಿ', encrypted: 'ಆರ್ ಬಿ ಐ ನಿಯಂತ್ರಿತ ಅಗ್ರಿಗೇಟರ್‌ನಿಂದ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ', enterOTP: 'OTP ನಮೂದಿಸಿ', sentTo: '+91 {{phone}} ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ', verify: 'ಪರಿಶೀಲಿಸಿ', discoveringFIPs: 'FIP ಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...', findingAccounts: 'ನಿಮ್ಮ ಲಿಂಕ್ ಮಾಡಲಾದ ಬ್ಯಾಂಕ್ ಖಾತೆಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ', accountsFound: 'ಖಾತೆಗಳು ಕಂಡುಬಂದಿವೆ', approveConsent: 'ಸಮ್ಮತಿಯನ್ನು ಅನುಮೋದಿಸಿ', consentNote: 'ಅನುಮೋದಿಸುವ ಮೂಲಕ, ನೀವು DEPA ಅಡಿಯಲ್ಲಿ ಸಮ್ಮತಿಗೆ ಡಿಜಿಟಲ್ ಸಹಿ ಮಾಡುತ್ತೀರಿ.', dataRequested: 'ವಿನಂತಿಸಿದ ಡೇಟಾ', summaryTxnProfiles: 'ಸಾರಾಂಶ, ವಹಿವಾಟುಗಳು, ಪ್ರೊಫೈಲ್‌ಗಳು', duration: 'ಅವಧಿ', oneYear: '1 ವರ್ಷ', fetchingData: 'ಡೇಟಾವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...', decryptingFI: 'ಹಣಕಾಸಿನ ಮಾಹಿತಿಯನ್ನು ಡಿಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ' },
};
export default kn;
