const mr = {
  common: {
    appName: 'फिनक्लेरियो', tagline: 'तुमच्या आर्थिक व्यवहारात स्पष्टता.', loading: 'लोड होत आहे...', save: 'जतन करा', cancel: 'रद्द करा', delete: 'हटवा', edit: 'संपादित करा', close: 'बंद करा', viewAll: 'सर्व पहा →', apply: 'लागू करा', reset: 'रीसेट', search: 'शोधा', filter: 'फिल्टर', filters: 'फिल्टर', export: 'निर्यात', download: 'डाउनलोड', email: 'ईमेल', password: 'पासवर्ड', signIn: 'साइन इन', signUp: 'साइन अप', signOut: 'साइन आउट', or: 'किंवा', allBanks: 'सर्व बँका', allCategories: 'सर्व श्रेणी', allTime: 'सर्व काळ', noData: 'डेटा उपलब्ध नाही', syncedJustNow: 'आत्ताच सिंक झाले', syncedAgo: '{{time}} मिनिटांपूर्वी सिंक', page: 'पृष्ठ', of: 'पैकी', showing: 'दाखवत आहे', total: 'एकूण',
  },
  nav: { dashboard: 'डॅशबोर्ड', transactions: 'व्यवहार', analytics: 'विश्लेषण', goals: 'उद्दिष्टे', insights: 'AI अंतर्दृष्टी', schemes: 'कर्ज आणि योजना', credit: 'क्रेडिट स्कोअर', reports: 'अहवाल', bankaa: 'बँक AA', alerts: 'सूचना', settings: 'सेटिंग्ज' },
  login: { title: 'डॅशबोर्डमध्ये साइन इन करा', createAccount: 'खाते तयार करा', emailLabel: 'ईमेल पत्ता', emailPlaceholder: 'you@example.com', passwordLabel: 'पासवर्ड', continueWithGoogle: 'Google सह सुरू ठेवा', noAccount: 'खाते नाही? साइन अप करा', hasAccount: 'आधीच खाते आहे? साइन इन करा', welcomeBack: 'पुन्हा स्वागत!', accountCreated: 'खाते यशस्वीरित्या तयार झाले!' },
  dashboard: { totalNetWorth: 'एकूण संपत्ती', inThisMonth: 'आय (या महिन्यात)', outThisMonth: 'खर्च (या महिन्यात)', doingGreat: 'तुम्ही छान करत आहात!', savingsHealthy: 'या महिन्यात तुमचा बचत दर निरोगी आहे!', connectedAccounts: 'जोडलेली खाती', linkViaSetu: 'Setu AA ने लिंक करा', addManualBank: 'मॅन्युअल बँक जोडा', availableBalance: 'उपलब्ध शिल्लक', recentTransactions: 'अलीकडील व्यवहार', noRecentTxns: 'अलीकडील व्यवहार सापडले नाहीत.' },
  txns: { title: 'सर्व व्यवहार', showingOf: '{{total}} पैकी {{filtered}} दाखवत आहे', exportCSV: 'CSV निर्यात', searchPlaceholder: 'व्यापारी, श्रेणी शोधा...', date: 'तारीख', merchant: 'व्यापारी / तपशील', category: 'श्रेणी', bank: 'बँक', amount: 'रक्कम', noMatch: 'कोणतेही व्यवहार जुळत नाहीत.', totalIn: 'एकूण आय', totalOut: 'एकूण खर्च', last7Days: 'मागील 7 दिवस', last30Days: 'मागील 30 दिवस', last90Days: 'मागील 90 दिवस' },
  analytics: { spentThisMonth: 'या महिन्यात खर्च', incomeThisMonth: 'या महिन्यात उत्पन्न', topCategory: 'शीर्ष श्रेणी', savingsRate: 'बचत दर', incomeVsExpense: 'उत्पन्न विरुद्ध खर्च', income: 'उत्पन्न', expense: 'खर्च', spendingSnapshot: 'खर्चाचा आढावा', totalSpent: 'एकूण खर्च', netSavingsGrowth: 'निव्वळ बचत वाढ', netSavings: 'निव्वळ बचत' },
  goals: { title: 'आर्थिक उद्दिष्टे', subtitle: 'बचत उद्दिष्टे ट्रॅक आणि व्यवस्थापित करा', newGoal: 'नवीन उद्दिष्ट', addNewGoal: 'नवीन उद्दिष्ट जोडा', goalName: 'उद्दिष्टाचे नाव', targetAmount: 'लक्ष्य रक्कम (₹)', currentSaved: 'सध्याची बचत (₹)', eta: 'अंदाजित वेळ', saveGoal: 'उद्दिष्ट जतन करा', target: 'लक्ष्य', goalReached: 'उद्दिष्ट गाठले! 🎉' },
  ai: { title: 'AI आर्थिक अंतर्दृष्टी', subtitle: 'तुमच्या खर्चाच्या डेटावरून बुद्धिमत्ता', spendingPrediction: '📈 खर्चाचा अंदाज', categoryIntelligence: '🧠 श्रेणी बुद्धिमत्ता', generatedInsights: '💡 तयार अंतर्दृष्टी', notEnoughData: 'अद्याप पुरेसा डेटा नाही', newInsights: '{{count}} नवीन' },
  schemes: { title: 'कर्ज आणि योजना', subtitle: 'वैयक्तिक अनुदान आणि कर्ज संधी शोधा', personalizedRec: 'वैयक्तिक शिफारसी', applyNow: 'आता अर्ज करा', viewDetails: 'तपशील पहा', match: 'जुळणी', all: 'सर्व', government: 'सरकारी', agriculture: 'शेती', education: 'शिक्षण', housing: 'गृहनिर्माण', business: 'व्यवसाय' },
  credit: { title: 'क्रेडिट प्रोफाइल', subtitle: 'तुमचे क्रेडिट आरोग्य समजून घ्या', experianScore: '📊 तुमचा एक्सपेरियन स्कोअर', veryGood: 'खूप चांगले', paymentHistory: 'पेमेंट इतिहास', creditUtilization: 'क्रेडिट वापर', totalAccounts: 'एकूण खाती', hardInquiries: 'कठीण चौकशा', highImpact: 'उच्च प्रभाव', lowImpact: 'कमी प्रभाव', scoreSimulator: '🔬 स्कोअर सिम्युलेटर', projectedScore: 'अंदाजित स्कोअर', simulatorDesc: 'पुढील 30 दिवसांत प्रभाव पाहण्यासाठी बदल करा.', payDebt: 'कर्ज ₹50,000 फेडा', payDebtDesc: 'क्रेडिट वापर कमी करते', newCard: 'नवीन क्रेडिट कार्डसाठी अर्ज करा', newCardDesc: 'तात्पुरती घसरण', missPayment: '30 दिवस पेमेंट चुकवा', missPaymentDesc: 'गंभीर प्रभाव' },
  reports: { title: 'आर्थिक अहवाल', subtitle: 'आर्थिक डेटा निर्यात आणि शेअर करा', reportType: 'अहवाल प्रकार', dateRange: 'तारीख श्रेणी', thisMonth: 'हा महिना', last3Months: 'मागील 3 महिने', includedAccounts: 'समाविष्ट खाती', allConnectedBanks: 'सर्व जोडलेल्या बँका', downloadPDF: 'PDF डाउनलोड', exportCSV: 'CSV निर्यात', emailToSelf: 'स्वतःला ईमेल करा', shareLink: 'लिंक शेअर करा', reportReady: 'तुमचा अहवाल तयार आहे.', incomeExpenseSummary: 'उत्पन्न आणि खर्च सारांश', taxSaving: 'कर बचत विवरण', allTransactions: 'सर्व व्यवहार यादी', categorySpend: 'श्रेणी खर्च विश्लेषण' },
  alerts: { title: 'सूचना आणि अलर्ट', subtitle: 'स्मार्ट अंतर्दृष्टी.', markAllRead: 'सर्व वाचलेले म्हणून चिन्हांकित करा', allClear: '✅ सर्व ठीक!', allClearDesc: 'सक्रिय अलर्ट नाहीत.', lowBalance: 'कमी शिल्लक चेतावणी', highSpending: 'जास्त खर्च आढळला', largeTransaction: 'मोठा व्यवहार अलर्ट', savingStreak: 'बचतीची मालिका!' },
  settings: { title: 'सेटिंग्ज', subtitle: 'खाते प्राधान्ये व्यवस्थापित करा.', saveChanges: 'बदल जतन करा', accountProfile: 'खाते प्रोफाइल', emailField: 'ईमेल', displayName: 'प्रदर्शन नाव', appPreferences: 'अॅप प्राधान्ये', darkTheme: 'डार्क थीम', darkThemeDesc: 'गडद इंटरफेसवर स्विच करा', pushAlerts: 'पुश अलर्ट', pushAlertsDesc: 'स्मार्ट सूचना मिळवा', defaultCurrency: 'डीफॉल्ट चलन', inr: 'भारतीय रुपया (₹)', usd: 'अमेरिकन डॉलर ($)', connectedDataSources: 'जोडलेले डेटा स्रोत', connectedDataDesc: 'डॅशबोर्डमध्ये समाविष्ट करायचे खाती निवडा.', monthlySpendingLimits: 'मासिक खर्च मर्यादा', language: 'भाषा', languageDesc: 'तुमची पसंतीची भाषा निवडा', settingsSaved: 'सेटिंग्ज जतन झाल्या', needOneBank: 'किमान एक बँक खाते जोडणे आवश्यक' },
  bankaa: { linkBankAccounts: 'तुमची बँक खाती लिंक करा', linkBankDesc: 'Setu Account Aggregator द्वारे सुरक्षितपणे कनेक्ट करा.', linkButton: 'माझी बँक खाती लिंक करा', rbiBadge: 'RBI नियमित', setuSandbox: 'Setu AA सँडबॉक्स', multiBankView: 'मल्टी-बँक दृश्य', multiBankViewDesc: 'एका डॅशबोर्डमध्ये अनेक बँक खाती', spendingAnalytics: 'खर्च विश्लेषण', spendingAnalyticsDesc: 'उत्पन्न vs खर्च ट्रॅक करा', bankGradeSecurity: 'बँक-ग्रेड सुरक्षा', bankGradeSecurityDesc: 'एंड-टू-एंड एन्क्रिप्शन', connectionError: 'कनेक्शन त्रुटी', creatingConsent: 'संमती विनंती तयार होत आहे...', connectingToSetu: 'Setu AA शी कनेक्ट होत आहे', openingConsent: 'संमती पृष्ठ उघडत आहे...', approveInTab: 'नवीन टॅबमध्ये मंजूर करा', waitingApproval: 'मंजुरीची प्रतीक्षा...', completeConsent: 'Setu टॅबमध्ये पूर्ण करा', fetchingData: 'बँक डेटा मिळवत आहे...', decryptingFI: 'आर्थिक माहिती डिक्रिप्ट होत आहे', cancelReset: 'रद्द आणि रीसेट', multiBankDashboard: 'मल्टी-बँक डॅशबोर्ड', accountsLinked: '{{count}} खाती लिंक', transactionsCount: '{{count}} व्यवहार', refresh: 'रिफ्रेश', relink: 'पुन्हा लिंक करा', totalBalance: 'एकूण शिल्लक', linkedAccounts: 'लिंक केलेली खाती', totalIncome: 'एकूण उत्पन्न', totalSpend: 'एकूण खर्च', balance: 'शिल्लक', combinedTransactions: 'एकत्रित व्यवहार', description: 'वर्णन', type: 'प्रकार', noTxnFilters: 'जुळणारे व्यवहार नाहीत.', incomeVsSpend: 'उत्पन्न विरुद्ध खर्च', netSavings: 'निव्वळ बचत', creditTxns: '{{count}} क्रेडिट व्यवहार', debitTxns: '{{count}} डेबिट व्यवहार' },
  setuModal: { verifyIdentity: 'ओळख सत्यापित करा', enterNumber: 'बँक खात्यांशी जोडलेला नंबर', mobileNumber: 'मोबाइल नंबर', sendOTP: 'OTP पाठवा', encrypted: 'RBI नियमित एन्क्रिप्शन', enterOTP: 'OTP टाका', sentTo: '+91 {{phone}} वर पाठवले', verify: 'सत्यापित करा', discoveringFIPs: 'FIP शोधत आहे...', findingAccounts: 'बँक खाती शोधत आहे', accountsFound: 'खाती सापडली', approveConsent: 'संमती द्या', consentNote: 'DEPA अंतर्गत डिजिटल स्वाक्षरी.', dataRequested: 'विनंती केलेला डेटा', summaryTxnProfiles: 'सारांश, व्यवहार, प्रोफाइल', duration: 'कालावधी', oneYear: '1 वर्ष', fetchingData: 'डेटा मिळवत आहे...', decryptingFI: 'आर्थिक माहिती डिक्रिप्ट' },
};
export default mr;
