const ta = {
  common: {
    appName: 'ஃபின்க்ளேரியோ', tagline: 'உங்கள் நிதியில் தெளிவு.', loading: 'ஏற்றுகிறது...', save: 'சேமி', cancel: 'ரத்து', delete: 'நீக்கு', edit: 'திருத்து', close: 'மூடு', viewAll: 'அனைத்தும் பார் →', apply: 'பயன்படுத்து', reset: 'மீட்டமை', search: 'தேடு', filter: 'வடிகட்டு', filters: 'வடிகட்டிகள்', export: 'ஏற்றுமதி', download: 'பதிவிறக்கு', email: 'மின்னஞ்சல்', password: 'கடவுச்சொல்', signIn: 'உள்நுழை', signUp: 'பதிவுசெய்', signOut: 'வெளியேறு', or: 'அல்லது', allBanks: 'அனைத்து வங்கிகள்', allCategories: 'அனைத்து வகைகள்', allTime: 'அனைத்து நேரம்', noData: 'தரவு இல்லை', syncedJustNow: 'இப்போது ஒத்திசைக்கப்பட்டது', syncedAgo: '{{time}} நிமிடங்கள் முன்', page: 'பக்கம்', of: 'இல்', showing: 'காட்டுகிறது', total: 'மொத்தம்',
  },
  nav: { dashboard: 'டாஷ்போர்ட்', transactions: 'பரிவர்த்தனைகள்', analytics: 'பகுப்பாய்வு', goals: 'இலக்குகள்', insights: 'AI நுண்ணறிவு', schemes: 'கடன்கள் & திட்டங்கள்', credit: 'கடன் மதிப்பெண்', reports: 'அறிக்கைகள்', bankaa: 'வங்கி AA', alerts: 'எச்சரிக்கைகள்', settings: 'அமைப்புகள்' },
  login: { title: 'டாஷ்போர்டில் உள்நுழையுங்கள்', createAccount: 'கணக்கை உருவாக்கு', emailLabel: 'மின்னஞ்சல் முகவரி', emailPlaceholder: 'you@example.com', passwordLabel: 'கடவுச்சொல்', continueWithGoogle: 'Google மூலம் தொடர்', noAccount: 'கணக்கு இல்லையா? பதிவு செய்', hasAccount: 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழை', welcomeBack: 'மீண்டும் வரவேற்கிறோம்!', accountCreated: 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது!' },
  dashboard: { totalNetWorth: 'மொத்த சொத்து மதிப்பு', inThisMonth: 'வரவு (இந்த மாதம்)', outThisMonth: 'செலவு (இந்த மாதம்)', doingGreat: 'நீங்கள் நன்றாகச் செய்கிறீர்கள்!', savingsHealthy: 'இந்த மாதம் உங்கள் சேமிப்பு விகிதம் ஆரோக்கியமாக உள்ளது!', connectedAccounts: 'இணைக்கப்பட்ட கணக்குகள்', linkViaSetu: 'Setu AA மூலம் இணை', addManualBank: 'கையேடு வங்கி சேர்', availableBalance: 'கிடைக்கும் இருப்பு', recentTransactions: 'சமீபத்திய பரிவர்த்தனைகள்', noRecentTxns: 'சமீபத்திய பரிவர்த்தனைகள் இல்லை.' },
  txns: { title: 'அனைத்து பரிவர்த்தனைகள்', showingOf: '{{total}} இல் {{filtered}} காட்டுகிறது', exportCSV: 'CSV ஏற்றுமதி', searchPlaceholder: 'வணிகர்கள், வகைகளை தேடு...', date: 'தேதி', merchant: 'வணிகர் / விவரங்கள்', category: 'வகை', bank: 'வங்கி', amount: 'தொகை', noMatch: 'பொருந்தும் பரிவர்த்தனைகள் இல்லை.', totalIn: 'மொத்த வரவு', totalOut: 'மொத்த செலவு', last7Days: 'கடந்த 7 நாட்கள்', last30Days: 'கடந்த 30 நாட்கள்', last90Days: 'கடந்த 90 நாட்கள்' },
  analytics: { spentThisMonth: 'இந்த மாதம் செலவு', incomeThisMonth: 'இந்த மாதம் வருமானம்', topCategory: 'முதல் வகை', savingsRate: 'சேமிப்பு விகிதம்', incomeVsExpense: 'வருமானம் vs செலவு', income: 'வருமானம்', expense: 'செலவு', spendingSnapshot: 'செலவு சுருக்கம்', totalSpent: 'மொத்த செலவு', netSavingsGrowth: 'நிகர சேமிப்பு வளர்ச்சி', netSavings: 'நிகர சேமிப்பு' },
  goals: { title: 'நிதி இலக்குகள்', subtitle: 'சேமிப்பு இலக்குகளை கண்காணிக்கவும்', newGoal: 'புதிய இலக்கு', addNewGoal: 'புதிய இலக்கு சேர்', goalName: 'இலக்கு பெயர்', targetAmount: 'இலக்கு தொகை (₹)', currentSaved: 'தற்போதைய சேமிப்பு (₹)', eta: 'மதிப்பிடப்பட்ட நேரம்', saveGoal: 'இலக்கை சேமி', target: 'இலக்கு', goalReached: 'இலக்கு அடையப்பட்டது! 🎉' },
  ai: { title: 'AI நிதி நுண்ணறிவு', subtitle: 'உங்கள் செலவு தரவிலிருந்து நுண்ணறிவு', spendingPrediction: '📈 செலவு கணிப்பு', categoryIntelligence: '🧠 வகை நுண்ணறிவு', generatedInsights: '💡 உருவாக்கப்பட்ட நுண்ணறிவுகள்', notEnoughData: 'போதிய தரவு இல்லை', newInsights: '{{count}} புதிய' },
  schemes: { title: 'கடன்கள் & திட்டங்கள்', subtitle: 'தனிப்பயன் மானியங்கள் மற்றும் கடன் வாய்ப்புகள்', personalizedRec: 'தனிப்பயன் பரிந்துரைகள்', applyNow: 'இப்போது விண்ணப்பி', viewDetails: 'விவரங்கள் காண்', match: 'பொருத்தம்', all: 'அனைத்தும்', government: 'அரசு', agriculture: 'விவசாயம்', education: 'கல்வி', housing: 'வீட்டுவசதி', business: 'வணிகம்' },
  credit: { title: 'கடன் சுயவிவரம்', subtitle: 'உங்கள் கடன் ஆரோக்கியத்தைப் புரிந்துகொள்ளுங்கள்', experianScore: '📊 எக்ஸ்பீரியன் மதிப்பெண்', veryGood: 'மிக நல்லது', paymentHistory: 'கட்டண வரலாறு', creditUtilization: 'கடன் பயன்பாடு', totalAccounts: 'மொத்த கணக்குகள்', hardInquiries: 'கடின விசாரணைகள்', highImpact: 'அதிக தாக்கம்', lowImpact: 'குறைந்த தாக்கம்', scoreSimulator: '🔬 மதிப்பெண் உருவகம்', projectedScore: 'மதிப்பிடப்பட்ட மதிப்பெண்', simulatorDesc: 'அடுத்த 30 நாட்களில் தாக்கத்தைக் காண மாற்றுங்கள்.', payDebt: 'கடன் ₹50,000 செலுத்து', payDebtDesc: 'கடன் பயன்பாட்டைக் குறைக்கிறது', newCard: 'புதிய கடன் அட்டைக்கு விண்ணப்பி', newCardDesc: 'தற்காலிக வீழ்ச்சி', missPayment: '30 நாள் கட்டணம் தவறவிடு', missPaymentDesc: 'கடுமையான தாக்கம்' },
  reports: { title: 'நிதி அறிக்கைகள்', subtitle: 'நிதி தரவை ஏற்றுமதி செய்', reportType: 'அறிக்கை வகை', dateRange: 'தேதி வரம்பு', thisMonth: 'இந்த மாதம்', last3Months: 'கடந்த 3 மாதங்கள்', includedAccounts: 'சேர்க்கப்பட்ட கணக்குகள்', allConnectedBanks: 'அனைத்து இணைக்கப்பட்ட வங்கிகள்', downloadPDF: 'PDF பதிவிறக்கு', exportCSV: 'CSV ஏற்றுமதி', emailToSelf: 'மின்னஞ்சல் அனுப்பு', shareLink: 'இணைப்பைப் பகிர்', reportReady: 'உங்கள் அறிக்கை தயார்.', incomeExpenseSummary: 'வருமானம் & செலவு சுருக்கம்', taxSaving: 'வரி சேமிப்பு அறிக்கை', allTransactions: 'அனைத்து பரிவர்த்தனை பட்டியல்', categorySpend: 'வகை செலவு பகுப்பாய்வு' },
  alerts: { title: 'அறிவிப்புகள் & எச்சரிக்கைகள்', subtitle: 'ஸ்மார்ட் நுண்ணறிவு.', markAllRead: 'அனைத்தையும் படித்ததாகக் குறி', allClear: '✅ எல்லாம் சரி!', allClearDesc: 'செயலில் எச்சரிக்கைகள் இல்லை.', lowBalance: 'குறைந்த இருப்பு எச்சரிக்கை', highSpending: 'அதிக செலவு கண்டறிந்தது', largeTransaction: 'பெரிய பரிவர்த்தனை எச்சரிக்கை', savingStreak: 'சேமிப்பு தொடர்!' },
  settings: { title: 'அமைப்புகள்', subtitle: 'கணக்கு விருப்பங்களை நிர்வகிக்கவும்.', saveChanges: 'மாற்றங்களைச் சேமி', accountProfile: 'கணக்கு சுயவிவரம்', emailField: 'மின்னஞ்சல்', displayName: 'காட்டப்படும் பெயர்', appPreferences: 'பயன்பாட்டு விருப்பங்கள்', darkTheme: 'டார்க் தீம்', darkThemeDesc: 'இருண்ட இடைமுகம்', pushAlerts: 'புஷ் எச்சரிக்கைகள்', pushAlertsDesc: 'ஸ்மார்ட் அறிவிப்புகள்', defaultCurrency: 'நாணயம்', inr: 'இந்திய ரூபாய் (₹)', usd: 'அமெரிக்க டாலர் ($)', connectedDataSources: 'இணைக்கப்பட்ட தரவு மூலங்கள்', connectedDataDesc: 'டாஷ்போர்டில் சேர்க்க கணக்குகளைத் தேர்ந்தெடு.', monthlySpendingLimits: 'மாதாந்திர செலவு வரம்புகள்', language: 'மொழி', languageDesc: 'விருப்ப மொழியைத் தேர்ந்தெடு', settingsSaved: 'அமைப்புகள் சேமிக்கப்பட்டன', needOneBank: 'குறைந்தது ஒரு வங்கி கணக்கை இணைக்க வேண்டும்' },
  bankaa: { linkBankAccounts: 'வங்கி கணக்குகளை இணைக்கவும்', linkBankDesc: 'Setu Account Aggregator மூலம் பாதுகாப்பாக இணைக்கவும்.', linkButton: 'எனது வங்கி கணக்குகளை இணை', rbiBadge: 'RBI ஒழுங்குபடுத்தப்பட்டது', setuSandbox: 'Setu AA சாண்ட்பாக்ஸ்', multiBankView: 'பல-வங்கி காட்சி', multiBankViewDesc: 'ஒரே டாஷ்போர்டில் பல கணக்குகள்', spendingAnalytics: 'செலவு பகுப்பாய்வு', spendingAnalyticsDesc: 'வருமானம் vs செலவை கண்காணி', bankGradeSecurity: 'வங்கி-தர பாதுகாப்பு', bankGradeSecurityDesc: 'எண்ட்-டு-எண்ட் குறியாக்கம்', connectionError: 'இணைப்பு பிழை', creatingConsent: 'ஒப்புதல் கோரிக்கை உருவாக்கப்படுகிறது...', connectingToSetu: 'Setu AA உடன் இணைக்கிறது', openingConsent: 'ஒப்புதல் பக்கம் திறக்கிறது...', approveInTab: 'புதிய தாவலில் ஒப்புக்கொள்', waitingApproval: 'ஒப்புதலுக்காகக் காத்திருக்கிறது...', completeConsent: 'Setu தாவலில் முடி', fetchingData: 'வங்கி தரவு பெறப்படுகிறது...', decryptingFI: 'நிதி தகவல் மறுகுறியீடு', cancelReset: 'ரத்து & மீட்டமை', multiBankDashboard: 'பல-வங்கி டாஷ்போர்ட்', accountsLinked: '{{count}} கணக்குகள் இணைக்கப்பட்டன', transactionsCount: '{{count}} பரிவர்த்தனைகள்', refresh: 'புதுப்பி', relink: 'மீண்டும் இணை', totalBalance: 'மொத்த இருப்பு', linkedAccounts: 'இணைக்கப்பட்ட கணக்குகள்', totalIncome: 'மொத்த வருமானம்', totalSpend: 'மொத்த செலவு', balance: 'இருப்பு', combinedTransactions: 'ஒருங்கிணைந்த பரிவர்த்தனைகள்', description: 'விவரம்', type: 'வகை', noTxnFilters: 'பொருந்தும் பரிவர்த்தனைகள் இல்லை.', incomeVsSpend: 'வருமானம் vs செலவு', netSavings: 'நிகர சேமிப்பு', creditTxns: '{{count}} வரவு பரிவர்த்தனைகள்', debitTxns: '{{count}} செலவு பரிவர்த்தனைகள்' },
  setuModal: { verifyIdentity: 'அடையாளத்தை சரிபார்', enterNumber: 'வங்கி கணக்குகளுடன் இணைக்கப்பட்ட எண்', mobileNumber: 'கைபேசி எண்', sendOTP: 'OTP அனுப்பு', encrypted: 'RBI ஒழுங்குபடுத்தப்பட்ட குறியாக்கம்', enterOTP: 'OTP உள்ளிடு', sentTo: '+91 {{phone}} க்கு அனுப்பப்பட்டது', verify: 'சரிபார்', discoveringFIPs: 'FIP கண்டறியப்படுகிறது...', findingAccounts: 'வங்கி கணக்குகளைக் கண்டறிகிறது', accountsFound: 'கணக்குகள் கண்டறியப்பட்டன', approveConsent: 'ஒப்புதல் அளி', consentNote: 'DEPA கட்டமைப்பின் கீழ் டிஜிட்டல் கையொப்பம்.', dataRequested: 'கோரப்பட்ட தரவு', summaryTxnProfiles: 'சுருக்கம், பரிவர்த்தனைகள், சுயவிவரங்கள்', duration: 'காலம்', oneYear: '1 ஆண்டு', fetchingData: 'தரவு பெறப்படுகிறது...', decryptingFI: 'நிதி தகவல் மறுகுறியீடு' },
};
export default ta;
